### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by s-charvin** [XcodesOrg/XcodesApp#549] opened 2024-04-08 05:25 UTC
**Describe the bug**
When I tried to log in to the apple id after downloading the new software, I received the verification code correctly, but every time I entered it, I was told that the verification code was incorrect.

**To Reproduce**
Just log in. But I turned on the VPN proxy.

**Expected behavior**
None

**Screenshots**
None

**Version**
 - OS: 13 latest
 - Xcodes:latest

**Comment by s-charvin** [comment] 2024-06-04 04:05
I may have found the cause of the problem. Because my account has two-factor authentication enabled, I receive a verification code via phone every time I log in. This may cause the program to fail even if I enter the correct verification code when logging in.

When I re-registered an account and my colleague did not turn on two-factor authentication and only received the verification code via SMS, the program could bind the Apple ID normally.

**Comment by czottmann** [comment] 2024-07-23 17:09
Duplicate of #439, I think.

**Comment by s-charvin** [comment] 2024-09-30 08:47
> Duplicate of #439, I think.

Yes.

**Closed** 2024-10-13 03:50 UTC
Labels: bug
