### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by ghost** [XcodesOrg/XcodesApp#578] opened 2024-06-13 05:12 UTC
**Describe the bug**
Login Failure.

**To Reproduce**
I am using YubiKey for two-factor authentication. When entering the ID and password, login fails.

**Screenshots**

![CleanShot 2024-06-13 at 14 07 46@2x](https://github.com/XcodesOrg/XcodesApp/assets/138769908/49f8d114-c5de-4627-a823-81b254f4036b)

**Comment by agoodkind** [comment] 2024-07-11 02:38
I am also experiencing this. 2FA enabled as well.

**Comment by czottmann** [comment] 2024-07-23 17:05
Duplicate of #439. Welcome to the party, folks ;)

**Closed** 2024-10-13 03:50 UTC
Labels: bug
